---
apiVersion: v1
kind: Service
metadata:
  name: notebook-validator-webhook-service
  namespace: jupyter-notebook-validator-operator-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: notebook-validator-mutating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: notebook-validator-webhook-service
      namespace: jupyter-notebook-validator-operator-system
      path: /mutate-mlops-mlops-dev-v1alpha1-notebookvalidationjob
  failurePolicy: Fail
  name: mnotebookvalidationjob.kb.io
  rules:
  - apiGroups:
    - mlops.mlops.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebookvalidationjobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: notebook-validator-validating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: notebook-validator-webhook-service
      namespace: jupyter-notebook-validator-operator-system
      path: /validate-mlops-mlops-dev-v1alpha1-notebookvalidationjob
  failurePolicy: Fail
  name: vnotebookvalidationjob.kb.io
  rules:
  - apiGroups:
    - mlops.mlops.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebookvalidationjobs
  sideEffects: None

