{{- if .Values.certManager.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "jupyter-notebook-validator-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyter-notebook-validator-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "jupyter-notebook-validator-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyter-notebook-validator-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
spec:
  dnsNames:
  - {{ include "jupyter-notebook-validator-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
  - {{ include "jupyter-notebook-validator-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "jupyter-notebook-validator-operator.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}

