{{- if .Values.validationRunner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.validationRunner.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyter-notebook-validator-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: validation-runner
  {{- with .Values.validationRunner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

