{{- if .Values.operator.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "jupyter-notebook-validator-operator.fullname" . }}-mutating-webhook
  labels:
    {{- include "jupyter-notebook-validator-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "jupyter-notebook-validator-operator.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "jupyter-notebook-validator-operator.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-mlops-mlops-dev-v1alpha1-notebookvalidationjob
  failurePolicy: {{ .Values.operator.webhook.failurePolicy }}
  name: mnotebookvalidationjob.kb.io
  rules:
  - apiGroups:
    - mlops.mlops.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebookvalidationjobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "jupyter-notebook-validator-operator.fullname" . }}-validating-webhook
  labels:
    {{- include "jupyter-notebook-validator-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "jupyter-notebook-validator-operator.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "jupyter-notebook-validator-operator.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-mlops-mlops-dev-v1alpha1-notebookvalidationjob
  failurePolicy: {{ .Values.operator.webhook.failurePolicy }}
  name: vnotebookvalidationjob.kb.io
  rules:
  - apiGroups:
    - mlops.mlops.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebookvalidationjobs
  sideEffects: None
{{- end }}

