{{- if .Values.operator.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter-notebook-validator-operator.webhookServiceName" . | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyter-notebook-validator-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.operator.webhook.port }}
  selector:
    {{- include "jupyter-notebook-validator-operator.selectorLabels" . | nindent 4 }}
{{- end }}

